### ISSUE TITLE
First Meeting (October 13)

### ISSUE THREAD

**Issue by ATOHANS** [ATOHANS/E-Commerce-Product-Management#8]
### Discussed in https://github.com/ATOHANS/E-Commerce-Product-Management/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **ATOHANS** October 13, 2024</sup>
We discussed the roles and how the platform should look like.</div>

**Comment by Kagaxan** [comment]
-test

**Comment by aiccrg** [comment]
tryy

**Comment by Marc2204** [comment]
<present>

**Comment by aiccrg** [comment]
<presentt>

**Comment by Marc2204** [comment]
present

**Comment by Jhiro4** [comment]
Present

**Comment by Kagaxan** [comment]
Present

**Comment by ATOHANS** [comment]
Product Owner: Hansel Ato
Scrum Master: Edward Alemania
Frontend Dev: Marc Buitizon
Backend Dev: Czernycrille Abellera
Tester: Jhiro Amarante
